idle_bg = "#1a1b26"
idle_fg = "#0db9d7"
info_bg = "#1a1b26"
info_fg = "#0db9d7"
good_bg = "#1a1b26"
good_fg = "#9ece6a"
warning_bg  = "#1a1b26"
warning_fg  = "#e0af68"
critical_bg = "#1a1b26"
critical_fg = "#f7768e"
separator = ""
separator_bg = "#1a1b26"
separator_fg = "#acb0d0"
